export const PHASES = {
  MENU: 'MENU',
  TRAINING_SETUP: 'TRAINING_SETUP',
  PASS_DEVICE_SHOOTER: 'PASS_DEVICE_SHOOTER',
  SHOOTER_TURN: 'SHOOTER_TURN',
  PASS_DEVICE_KEEPER: 'PASS_DEVICE_KEEPER',
  KEEPER_TURN: 'KEEPER_TURN',
  ANIMATING_3D: 'ANIMATING_3D',
  RESULT: 'RESULT',
  GAME_OVER: 'GAME_OVER',
};

export const ACTIONS = {
  START_GAME: 'START_GAME',
  START_TRAINING: 'START_TRAINING',
  READY_SHOOTER: 'READY_SHOOTER',
  SELECT_SHOOT_ZONE: 'SELECT_SHOOT_ZONE',
  READY_KEEPER: 'READY_KEEPER',
  SELECT_KEEP_ZONE: 'SELECT_KEEP_ZONE',
  ANIMATION_COMPLETE: 'ANIMATION_COMPLETE',
  NEXT_SHOT: 'NEXT_SHOT',
  RESET_GAME: 'RESET_GAME',
  SET_SCREEN_SHAKE: 'SET_SCREEN_SHAKE',
};

export const RESULTS = {
  GOAL: 'goal',
  SAVE: 'save',
};

export const isGoal = (r) => r === RESULTS.GOAL;
export const isSave = (r) => r === RESULTS.SAVE;
